apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.bitbucket.deploy_name }}
  labels:
    {{- include "bitbucket.labels" . | indent 2 }}
spec:
  replicas:  {{ .Values.bitbucket.replicas }}
  selector:
    matchLabels:
   {{- include "bitbucket.selector"  . | indent 2 }}
  template:
    metadata:
      labels:
     {{- include "bitbucket.template_labels" . | indent 4 }}
    spec:
      containers:
      - name:  {{ .Values.bitbucket.container_name }}
        image: "{{ .Values.bitbucket.image }}:{{ .Values.bitbucket.image_tag }}"
        ports:
        - containerPort: {{ .Values.bitbucket.container_port }}
        livenessProbe:
          {{- toYaml .Values.bitbucket.probes.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.bitbucket.probes.readinessProbe | nindent 10 }}     
        resources:
          requests:
          {{- toYaml .Values.bitbucket.resources.requests | nindent 12 }}   
          limits:
          {{- toYaml .Values.bitbucket.resources.limits | nindent 12 }}  
        volumeMounts:
        {{- toYaml .Values.bitbucket.volumeMounts | nindent 8 }} 
      volumes:
      {{- toYaml .Values.bitbucket.volumes | nindent 6 }} 
